services:
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d/tasks.localhost.com.conf:/etc/nginx/conf.d/task.localhost.com.conf
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  taskapi:
    image: back
    ports:
      - 3001:3001
  frontend:
    build: front
    ports:
      - 3000:3000


