services:
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d/tasks.localhost.com.conf:/etc/nginx/conf.d/task.localhost.com.conf
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    network_mode: host
  taskapi:
    build: ./backend
    ports:
      - 3001:3001
    network_mode: host
  frontend:
    build: ./fronted
    ports:
      - 3000:3000
    network_mode: host


